import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeToaster } from "@/components/theme-toaster";
import { ImageKitProvider } from "@imagekit/next";


const urlEndPoint = process.env.NEXT_PUBLIC_IMAGEKIT_ENDPOINT!

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agri-Grocer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ImageKitProvider urlEndpoint={urlEndPoint}>
            <ThemeToaster />
            {children}
          </ImageKitProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
