name: Build & Push Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        run: |
          docker build --no-cache \
            -f docker/base.Dockerfile \
            -t parzivalprime/my-node-base:latest .
          docker push parzivalprime/my-node-base:latest

      - name: Build deps image
        run: |
          docker build \
            -f docker/deps.Dockerfile \
            -t parzivalprime/my-node-deps:latest .
          docker push parzivalprime/my-node-deps:latest

      - name: Build api-gateway
        run: |
          docker build --no-cache \
            -f apps/api-gateway/Dockerfile \
            -t parzivalprime/api-gateway:latest .
          docker push parzivalprime/api-gateway:latest

      - name: Build auth-service
        run: |
          docker build --no-cache \
            -f apps/auth-service/Dockerfile \
            -t parzivalprime/auth-service:latest .
          docker push parzivalprime/auth-service:latest

      - name: Build product-service
        run: |
          docker build --no-cache \
            -f apps/product-service/Dockerfile \
            -t parzivalprime/product-service:latest .
          docker push parzivalprime/product-service:latest

      - name: Build order-service
        run: |
          docker build --no-cache \
            -f apps/order-service/Dockerfile \
            -t parzivalprime/order-service:latest .
          docker push parzivalprime/order-service:latest

      - name: Build kafka-service
        run: |
          docker build --no-cache \
            -f apps/kafka-service/Dockerfile \
            -t parzivalprime/kafka-service:latest .
          docker push parzivalprime/kafka-service:latest
      
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu/app/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app

            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
            echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
            echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
            echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
            echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
            echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
            echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
            echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
            echo "SMTP_SERVICE=${{ secrets.SMTP_SERVICE }}" >> .env
            echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
            echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
            echo "IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }}" >> .env
            echo "IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }}" >> .env
            echo "KAFKA_API_KEY=${{ secrets.KAFKA_API_KEY }}" >> .env
            echo "KAFKA_API_SECRET=${{ secrets.KAFKA_API_SECRET }}" >> .env
            echo "USER_UI_URL=${{ secrets.USER_UI_URL }}" >> .env
            echo "SELLER_UI_URL=${{ secrets.SELLER_UI_URL }}" >> .env
            echo "PRODUCT_SERVICE_URL=${{ secrets.PRODUCT_SERVICE_URL }}" >> .env
            echo "ORDER_SERVICE_URL=${{ secrets.ORDER_SERVICE_URL }}" >> .env
            echo "AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}" >> .env

            docker compose down 
            docker pull parzivalprime/api-gateway:latest
            docker pull parzivalprime/auth-service:latest
            docker pull parzivalprime/product-service:latest
            docker pull parzivalprime/order-service:latest
            docker pull parzivalprime/kafka-service:latest
            docker compose up -d
